#!/bin/sh
#/ script/actionslog builds and runs the project with the given arguments.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go build -o bin/actionslog ./cmd/actionslog

exec bin/actionslog "$@"
