#!/bin/sh
#/ script/lint runs linters on the project.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

script/bindown -q install shellcheck

# install golangci-lint from source to avoid conflicts with go versions while 1.21 is still a rc
GOBIN="$(pwd)"/bin go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

bin/golangci-lint run ./...
bin/shellcheck script/*
