#!/bin/sh
#/ script/lint runs linters on the project.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

script/bindown -q install shellcheck golangci-lint

bin/golangci-lint run ./...
bin/shellcheck script/*
